INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Product 1', 100);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Product 2', 200);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Product 3', 300);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Product 4', 400);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Product 5', 500);
